PHASE_INIT_RUNS = 'init_run'
PHASE_INIT_NN = 'init_nn'
PHASE_COMPUTATION = 'computation'
PHASE_SUCCESS = 'success'
PHASE_NEXT_RUN_WAITING = 'next_run_waiting'

MODE_TRAIN = 'train'
MODE_VALIDATION = 'validation'
MODE_TEST = 'test'
MODE_VALIDATION_WAITING = 'validation_waiting'
MODE_TRAIN_WAITING = 'train_waiting'
